### ISSUE TITLE
[Question] Session logs in High Availability

### ISSUE THREAD

**Issue by yanivyalda** [treasure-data/digdag#1232]
I'm wondering if anyone can provide assistance with a question regarding running digdag in High availability mode.

We have 2 Master nodes (running UI, API and --disable-local-agent --disable-executor-loop)
We have X Agent nodes ( --disable-scheduler )

The agent's are using log-server.type=s3

When dag's run the logs are saved to the s3 bucket. 
When viewing the session via the UI on the Master nodes, we **cant** see the logs. Only if we go to the Agent host can we see the logs.

Is there a reason why /api/sessions/xxx/files returns [] on the master nodes?

**Comment by yoyama** [comment]
@yanivyalda I guess there is no API '/api/sessions/xxx/files'. 
Do you mean  '/api/logs/{attempt_id}/files' ?
Then your question is that '/api/logs/{attempt_id}/files' does not work in your master node?

It is uncertain that the cause is in UI or API from your question. You can check API result by curl or you can use digdag cli to check API. Then we can determine the cause.

You can also check server log with increasing log level and which options does affect to behavior remove --disable-local-agent or --disable-executor-loop in master nodes.

**Comment by yanivyalda** [comment]
hi @yoyama yes sorry I mean /api/logs/{attempt_id}/files is empty on master node

I am using the API to test this. 

I did remove --disable-local-agent and now I can see the logs on master but 
/api/logs/335/files on master  != /api/logs/335/files on agent
why could this be? corrupt database?

**Comment by yanivyalda** [comment]
I had a corrupt db, its working fine now.

removing --disable-local-agent allowed me to view the s3 logs on all running instances
