### ISSUE TITLE
running digdag server with postgres database

### ISSUE THREAD

**Issue by spaskob** [treasure-data/digdag#1363]
Hi, could someone explain how to run the server in postgres mode. I could not find it in the docs.

Thank you!

**Comment by hiroyuki-sato** [comment]
Hello, @spaskob 

Thank you for trying Digdag.
Could you try these steps?


## Server configuration

```
$ psql -h host -U super_user -d postgres
postgres=# CREATE ROLE digdag WITH PASSWORD 'digdagpass' NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN;
CREATE ROLE
postgres=# CREATE DATABASE digdag_db WITH OWNER digdag;
CREATE DATABASE
postgres=# CREATE EXTENSION "uuid-ossp";
CREATE EXTENTION
```


create configuration file (ex. `server.properties`)

```
database.type = postgresql
database.user = digdag
database.password = digdagpass
database.host = <PostgreSQL host>
database.port = <PostgreSQL port>
database.database = digdag_db
```

Add secret encryption key into configuration file.
The secret encryption key is used to encrypt secrets when they are stored in the digdag server database. It must be a valid 128-bit AES key, base64 encoded.

```
digdag.secret-encryption-key = MDEyMzQ1Njc4OTAxMjM0NQ==
# example
echo -n '16_bytes_phrase!' | openssl base64
MTZfYnl0ZXNfcGhyYXNlIQ==
```


launch server

```
digdag server --config server.properties -O logs/tasklogs -A logs/accesslogs -L logs/server.log
```

## Client test

```
digdag init -t sh hello
cd hello
digdag push sample
digdag start sample hello --session now
```


## Reference

* [Digdag Serverのインストール手順](https://qiita.com/bwtakacy/items/ec3151644512ca65f6b6) Japanese [Google translate](https://translate.google.com/translate?hl=&sl=ja&tl=en&u=https%3A%2F%2Fqiita.com%2Fbwtakacy%2Fitems%2Fec3151644512ca65f6b6)
* [Secret Encryption Key](http://docs.digdag.io/command_reference.html#secret-encryption-key)
* [Server-mode commands](http://docs.digdag.io/command_reference.html#server-mode-commands)

**Comment by spaskob** [comment]
Thank you this worked!

**Comment by yoyama** [comment]
The issue had been resolved. So closed.

**Comment by revanna7226** [comment]
@hiroyuki-sato,
Hope you are doing great!

I have used tried to interface Digdag with Postgresql. Digdag and Postgres are installed on two different Linux Servers.
I followed your procedure below to create database for Digdag.
$ psql -h host -U super_user -d postgres
postgres=# CREATE ROLE digdag WITH PASSWORD 'digdagpass' NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN;
CREATE ROLE -- worked fine
postgres=# CREATE DATABASE digdag_db WITH OWNER digdag;
CREATE DATABASE -- worked fine
postgres=# CREATE EXTENSION "uuid-ossp";
CREATE EXTENTION -- Did not work. ERROR:  could not open extension control file "/usr/pgsql-13/share/extension/uuid-ossp.control": No such file or directory

I ignored the installation of "uuid-ossp" and set up the postgres configurations in server.properties file of Digdag.

Secret key also added.

But while running the server Digdag ending up with the below error.
Jul 27 15:30:55 melcoq1.localdomain java[6190]: while locating io.digdag.core.agent.TaskCallbackApi
Jul 27 15:30:55 melcoq1.localdomain java[6190]: Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.

Could you please help me why is this?

Thanks and Regards,
Revanna
