### ISSUE TITLE
retry --resume with a new revision resumes tasks that have changed

### ISSUE THREAD

**Issue by danielnorberg** [treasure-data/digdag#144]
When digdag resumes tasks from an earlier attempt that is being retried, it naively reuses all tasks with the same name, regardless of if the operator or configuration has changed. This limits the usefulness of the retry command.

Here is one (perhaps slightly contrived) example of a scenario where this might be problematic.

```
# Revision 1

+expensive:
 ... # expensive (e.g. very time consuming) tasks that the user does not want to retry.

+prepare:
  td>: prepare.sql  # data preparation query produces incorrect output ...
  create_table: prepared

+process:
  td>: process.sql  # ... in such a way that the data processing query fails
  create_table: processed
```

The user runs the above workflow and the attempt fails. The user fixes the issue in the `prepare` query pushes revision 2.

```
# Revision 2

+expensive:
 ... # expensive (e.g. very time consuming) tasks that the user does not want to retry.

+prepare:
  td>: prepare.sql  # The bug is now fixed. Output is correct.
  create_table: prepared

+process:
  td>: process.sql  # But the data processing query still fails because the fixed preparation task is not executed.
  create_table: processed
```

The user then does a `digdag retry --resume --latest-revision` but the retry fails because the incorrect output from the `+prepare` task is reused as-is as the `+prepare` task is "resumed".

One could argue that the user should have been more careful in inspecting the state of tasks in the attempt being retried and have been more aware of the actual implications of using `--resume`. Instead they should perhaps have used `--resume-from` to ensure that `+prepare` is re-executed in the retry. However, it is easy to imagine an example scenario where `--resume-from` will not be able to solve the problem.

It might be more useful to the user if digdag could automatically understand that `+prepare` should have been re-executed (instead of "resumed") because the contents of `prepare.sql` had changed.

The above scenario is the best case failure as the user notices that the retry fails and can troubleshoot.

A worse scenario is where the unexpected reuse (resumption) of a task from an earlier attempt causes the new attempt to succeed and silently produce an incorrect result that does not match what the result of `retry --all` would be.

**Comment by frsyuki** [comment]
Right. So `--resume` should not be the default.
* As a quick fix, the name is too short. `--skip-succeeded`, `--retry-only-failed`, or `--resume-failed` is better. Do you have suggestion about the naming? I think `--skip-succeeded` is good.
* Resuming is complicated work. I think GUI works well for this case. Users choose which task should be skipped, and it sends actual list of task IDs to skip. But building this UI is hard (at least for me).
* I think we should recommend `--resume-from` more. It is more explicit. It doesn't cause unexpected behavior. Although it's not powerful enough to support all parallel execution cases, it's relatively rare.
* I think automatic retry doesn't work well because:
  * If change of _export at a parent task does NOT retry children tasks, following tasks will get unexpected parameters.
  * If change of _export a a parent task retries children tasks, it could be unexpected for users because a lot of long-running tasks may run again.
  * Not many workflow definitions are idempotent. Retrying unexpected tasks may load data twice, etc. Making tasks failed is more acceptable.
* Retry command should support `--dry-run` so that users can know which tasks will run and how they will run visually in advance.
* `--dry-run` gives a basic execution plan. If it's not good, user should be able to use `--skip <+name>` and `--retry <+name>` options for each specific task.

A bad thing for this manual / explicit approach is that setting task names one by one is hard as workflow becomes complicated. But resuming is more useful if workflow is more complicated. However, because of that, complex syntax should be acceptable for those complicated workflows. So, here is another idea especially for command line:

1. Users put checkpoints in workflow definition. For example, here is fairly complicated workflow:

```
_export:
  td:
    database: user_analytics_${session_date_compact}

+prepare_db:
  td_ddl>:
  drop_databases: [${td.database}]

+load:
  _parallel: true
  +load_api_db:
    td_load>: ...
  +load_plazma_stats:
    +distribute:
      loop>: 4
      _parallel: true
      _do:
        +make_replica:
          sh>: ...
        +load_from_replica:
          td_load>: ...
        +shutdown_replica:
          sh>: ...
  +load_worker_db_status:
    td_load>: ...
  _checkpoint: data_loaded

+analyze:
  +data_sets:
    _parallel: true
    +make_user_id_table:
      td>: ...
    +make_data_set_stats:
      td>: ...
    _checkpoint: data_sets_done
  +analyze:
    td>: ...
  +analyze2:
    td>: ...
  +aggregate:
    td>: ...
    _checkpoint: result_ready
  +push_to_tableau:
    td>: ...
```

2. When a workflow runs, it records which checkpoint is successfully passed.

3. If user types `digdag retry --resume-checkpoints`, it skips tasks before successful checkpoints. This is powerful automation. If at least one task before "data_loaded" fails, all tasks before that will be retried.

4. If user types `digdag retry --retry-checkpoint <name>`, it skips tasks before that checkpoint. This is almost same with --resume-from but brings better organization. For example, users know something is changed in data loading part at the latest revision, the user will use `--retry-checkpoint data_loaded`. This retries +prepare_db and +load.

5. Users should also also use --dry-run and --skip/--retry to modify the basic plan.

6. Checkpoints are also good to know basic status of a session. We can show something like this:

````
Checkpoints:
+-----------------+---------+
| Checkpoint      | Status  |
+-----------------+---------+
| data_loaded     | SUCCESS |
| data_sets_done  | FAILED  |
| result_ready    |         |
+-----------------+---------+
```

And after retrying:

```
+-----------------+---------+
| Checkpoint      | Status  |
+-----------------+---------+
| data_loaded     | SKIPPED |
| data_sets_done  | SUCCESS |
| result_ready    | RUNNING |
+-----------------+---------+
```

**Comment by danielnorberg** [comment]
I believe that automatic caching/reuse/resumption for retries/reruns is a powerful differentiating feature that users will appreciate if we can make it easy enough to use. We need to find a good balance between ease of use, reliability and ease of reasoning about expected results.

My initial thought is to try and make the automatic resumption mechanism more intelligent by mimicking the Docker build caching behavior. Compute digests of the inputs and configuration of tasks and rerun tasks whose digests have changed. Include digests of upstream tasks in the computation of a task digest. This means that a change in an upstream task will cause downstream tasks to be rerun. This is akin to an automatic `--resume-from` where digdag will automatically rerun all tasks from the earliest point of change in the workflow, with the added benefit that this will work as expected for parallel workflows. The user is liberated from having to manually keep track of where they made changes to the workflow and it seems to me to be a mechanism that is relatively easy to reason about. It should also be relatively simple to implement. Am I missing something?

My second thought is like you say, a UI that gives the user more detailed control over individual tasks might be good, especially if it can indicate to the user what tasks have changed (using digests like above) in the latest revision. The user could then open the session in the UI and select what tasks to rerun. The UI could have a button like "select changed tasks" to combine both automation and fine grained control. An open question would be how this would scale to large workflows with hundreds or thousands of tasks but there might be ways to build a UI that can scale to handle that as well.

**Comment by yoyama** [comment]
Close the old issue. Please reopen or file new one if you need.
