### ISSUE TITLE
Unable to exit as success status when using sys.exit(0) from py:> operator

### ISSUE THREAD

**Issue by s-furu** [treasure-data/digdag#1771]
digdag 0.10.4
python 3.9.2

I want to exit from py file as success status, 
but the bellow script does not finish as success status but as failure status.

```
import sys

def success_job():
    sys.exit(0)
```
The error message is here.
```
Error messages from python: Failed to call python command with code:0 Possible cause: Ivalid python module call, duplicae module name with standard library (SystemExit)
```
Is any module in Java interfering with python sys module?

**Comment by hiroyuki-sato** [comment]
Hello, @s-furu 

I think you can't use `sys.exit` because `py>` operator use [`runner.py`](https://github.com/treasure-data/digdag/blob/master/digdag-standards/src/main/resources/digdag/standards/py/runner.py#L150-L173). It calls your script.

What do you think about using `return` instead of `sys.exit`?

The following example doesn't raise an exception.

```python
class MyClass(object):
    def print_time(self):
        return
        raise Exception("HOGEHOGE")
```

```yaml
timezone: UTC

+setup:
  py>: scripts.myclass.MyClass.print_time
```

Otherwise, you can use `sh>` operator.

**Comment by s-furu** [comment]
Hi @hiroyuki-sato,

I understand the internal process.
Thank you for the navigation and the alternative manner!
