### ISSUE TITLE
javascript re-evaluated each time it's referenced

### ISSUE THREAD

**Issue by westwick** [treasure-data/digdag#351]
Consider this workflow:

```
_export:
  starttime: ${moment().unix()}

+start:
  sh>: "echo ${starttime}"

+do_something:
  td>: ....

+end:
  sh>: "echo ${starttime}"
```

`${starttime}` is evaluated each time and thus produces different values. Logically I would assume assigning a variable at the start would make that variable constant throughout the workflow. Is this intended, and if so, is there a different way to accomplish what I'm trying to do?

**Comment by frsyuki** [comment]
That is a good question...Yes, `${...}` is evaluated each time currently. This is because JavaScript runs only when a task starts and doesn't run when _export is set. However, I understand that it is somewhat surprising behavior. Thus we might want to change it.

A workaround is using `for_each` operator to pre-evaluate variables:

```
+pre_eval:
  for_each>:
    starttime: ["${moment().unix()}"]
  _do:
    +start:
      sh>: "echo ${starttime}"

    +do_something:
      td>: ....

    +end:
      sh>: "echo ${starttime}"
```

Following syntax is possible since #290 (v0.8.15) to remove extra indent to all operators:


```
# start.dig

+pre_eval:
  for_each>:
    starttime: ["${moment().unix()}"]
  _do:
    call>: main.dig
```

```
# main.dig
+start:
  sh>: "echo ${starttime}"

+do_something:
  td>: ....

+end:
  sh>: "echo ${starttime}"
```

**Comment by westwick** [comment]
Thanks for the workaround :)
