### ISSUE TITLE
CLI broken on fish shell

### ISSUE THREAD

**Issue by drobakowski** [treasure-data/digdag#426]
It seems as `digdag` is not compatible with fish shell at the moment. Trying to run `digdag` from a fish shell results in the following error message:

```sh
Failed to execute process '/Users/david/bin/digdag'. Reason:
exec: Exec format error
The file '/Users/david/bin/digdag' is marked as an executable but could not be run by the operating system.
```
I'm running on macOS Sierra:
```
Darwin 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```
Running `digdag` on my system with a bash shell works fine.

**Comment by hiroyuki-sato** [comment]
You can use `java -jar /path/to/digdag` instead on the fish environment. 

The digdag designed to run as single binary on Windows and Unix platform.
It is using a hackky technique(It use Embulk too. )

It doesn't use shebang '#!'. Maybe that's why it raise that error. 

Please see this slide (especially page 41)
http://www.slideshare.net/frsyuki/fighting-against-chaotically-separated-values-with-embulk/40

**Comment by hiroyuki-sato** [comment]
## Error case 

```bash

echo "test"
```

```
./test.sh
Failed to execute process './test.sh'. Reason:
exec: Exec format error
The file './test.sh' is marked as an executable but could not be run by the operating system.
```

## OK case

```bash
#!/bin/sh
echo "test"
```

```
./test.sh
test
```

## Environment

* FISH_VERSION: 2.4.0
* OS: macOS 10.12.1

**Comment by drobakowski** [comment]
Thanks @hiroyuki-sato for your fast response! I've tried a fresh install of `digdag` through `brew` and it seems to be fixed already with the newest version.
