### ISSUE TITLE
[Q] Define variables for parallel tasks in "for_each" by `Digdag.env.store`

### ISSUE THREAD

**Issue by odaillyjp** [treasure-data/digdag#488]
I'd like to define variables for subtasks in the for_each syntax by `Digdag.env.store`.
When several tasks in "for_each" run in parallel, does the variables defined by `Digdag.env.store` change in the each parallel tasks?
if it is, is there any way to define unchangeable variables in Ruby?

workflow.dig
```
_export:
  directories: ["foo", "bar"]
  rb:
    require: "workflow"

+for_items:
  for_each>:
    dir: ${directories}
  _parallel:
    true
  _do:
    +for_item:
      +config:
        rb>: Workflow.config

      +for_paths:
        for_each>:
          path: ${paths}
        _do:
          +task:
            sh>: echo "run ${path}"
```

workflow.rb
```
class Workflow
  def config(dir)
    paths = Dir.glob("#{dir}/*")
    Digdag.env.store(paths: paths)
  end
end
```

**Comment by frsyuki** [comment]
> does the variables defined by Digdag.env.store change in the each parallel tasks?

No.
A variable stored by a task is visible only from tasks which depend on the storing task directly or indirectly.

For example, your workflow creates following tasks (you can find them in execution log):

```
1. +workflow+for_items): for_each>: {dir=["foo","bar"]}
2. +workflow+for_items^sub+for-0=dir=0=foo+for_item+config): rb>: Workflow.config
3. +workflow+for_items^sub+for-0=dir=1=bar+for_item+config): rb>: Workflow.config
4. +workflow+for_items^sub+for-0=dir=1=bar+for_item+for_paths): for_each>: {path=["bar/bar1","bar/bar2"]}
5. +workflow+for_items^sub+for-0=dir=0=foo+for_item+for_paths): for_each>: {path=["foo/foo1","foo/foo2"]}
6. +workflow+for_items^sub+for-0=dir=1=bar+for_item+for_paths^sub+for-0=path=0=bar%2Fbar1+task): sh>: echo "run bar/bar1"
7. +workflow+for_items^sub+for-0=dir=0=foo+for_item+for_paths^sub+for-0=path=0=foo%2Ffoo1+task): sh>: echo "run foo/foo1"
8. +workflow+for_items^sub+for-0=dir=1=bar+for_item+for_paths^sub+for-0=path=1=bar%2Fbar2+task): sh>: echo "run bar/bar2"
9. +workflow+for_items^sub+for-0=dir=0=foo+for_item+for_paths^sub+for-0=path=1=foo%2Ffoo2+task): sh>: echo "run foo/foo2"
```

In this execution, task 2 stores `path=["foo/foo1", "foo/foo2"]`, and task 3 stores `path=["bar/bar1", "bar/bar2"]`. Because `_parallel: true` option is set, task 2 and task 3 don't depend on each other (and thus they run in parallel). Dependency graph looks as following (`<-` means "depends on"):

* 1 <- 2 <- 4 <- 5 <- 6
* 1 <- 3 <- 7 <- 8 <- 9

Variables stored by task 2 are visible by task 5 and 6 because they depend on task 2 indirectly. Task 8 and 9 don't see variables stored by task 2 or 4 because task 8 and 9 don't depend on task 2 at all. When task 4 stores a variable, task 8 and 9 can't see it because they don't depend on task 4.

---

If you don't set `_parallel: true`, dependency graph becomes as following:

* 1 <- 2 <- 4 <- 5 <- 6 <- 3 <- 7 <- 8 <- 9

In this case, when task 4 stores a variable, it's visible by 8 and 9.

**Comment by odaillyjp** [comment]
Thank you, I could understand about variables stored by a task.
