### ISSUE TITLE
Digdag workflows command should show the original definition file

### ISSUE THREAD

**Issue by rbparrish** [treasure-data/digdag#72]
running `digdag workflows <project_name> +<workflow_name>` should show the original file, not a slightly deviated version of it. Including any comments or other notations included.

**Comment by frsyuki** [comment]
I don't find particular demands for this functionality for now. Within the "deviated" version, keeping comments sounds good idea but reformatting could be still better.
I think that what people want to have is rather a command that downloads the project archive file so that they can see all files including query files, script files, and .dig files. At least I want it.

**Comment by yoyama** [comment]
I will close this because the discussion stop for long time.
But feel free to reopen if need.
