### ISSUE TITLE
Embedding environment variables in config files

### ISSUE THREAD

**Issue by danielnorberg** [treasure-data/digdag#79]
Currently `~/.digdag/config` is a java properties file. It would be convenient to use the HOCON format and the typesafe config library to allow for things like: 

```
email {
  host: smtp.foo.bar
  user: ...
  ....
}
```

And to gain useful functionality like system property and environment variable substitution for free.

**Comment by frsyuki** [comment]
I think we should use YAML because .dig files are YAML. Having multiple configuration formats (YAML, Java properties file, secrets, and HOCON) makes it difficult to learn the system. We should keep them as consistent as possible.
To embed environment variables, we can use the same config format with .dig (`${ENV_VAR_NAME}` format).

**Comment by yoyama** [comment]
I close this issue but feel free to reopen if need
