### ISSUE TITLE
[issue] python digdag.env.export seems not working (2)

### ISSUE THREAD

**Issue by sonots-zozo** [treasure-data/digdag#944]
Reopen the issue https://github.com/treasure-data/digdag/issues/170

The example tells how to use `digdag.env.export`, but it seems not working because the `+dependent1` task is not a child of `+set_export` task.
https://github.com/treasure-data/digdag/blob/19dfc0c00e980a6d2c7dfb0f65cc66d62ac63268/examples/params.dig#L47-L56

The result was as:

```
2019-01-22 16:15:07 +0900 [INFO] (0017@[0:default]+params+export_params_2+set_export): py>: examples.params.set_export
2019-01-22 16:15:07 +0900 [INFO] (0017@[0:default]+params+export_params_2+dependent1): py>: examples.params.show_export
show_export: table = None
```

although it aims to set `table = carried information`.

How can we use `digdag.env.export`, then? In my understanding, following .dig is also prohibited.

```
timezone: UTC

+export_params:
  py>: params.set_export

  +dependent1:
    py>: params.show_export
```

**Comment by yoyama** [comment]
How about using **digdag.env.store** instead of **digdag.env.export** ?

**params.py**
```python
from __future__ import print_function
import digdag

def set_export():
    digdag.env.export({"table": "carried information"})

def set_store():
    digdag.env.store({"table": "carried information"})

def show_export(table=None):
    print("show_export: table = " + str(table))

```
**show1.sh**
```
#!/bin/bash                                                                                                                  

echo "table = $table"
```

**test1.dig**
```
timezone: UTC

+export_params:
  py>: params.set_store

+task1:
  py>: params.show_export

+task2:
  sh>: ./show1.sh

```

Results:
```
2019-01-22 17:02:28 +0900 [INFO] (0017@[0:default]+test1+export_params): py>: params.set_store
2019-01-22 17:02:29 +0900 [INFO] (0017@[0:default]+test1+task1): py>: params.show_export
show_export: table = carried information
2019-01-22 17:02:29 +0900 [INFO] (0017@[0:default]+test1+task2): sh>: ./show1.sh
table = carried information
Success.
```

**Comment by sonots** [comment]
I am asking how to use `digdag.env.export` here. I mean that I am doubting its functionality is not working.

(Also, digdag.env.store shows the parameters set at Digdag Web UI. So, we can not use it to map digdag secrets to environment variables).

**Comment by yoyama** [comment]
As you mentioned, I also think the example does not work.
I think if we want to refer variables which are set by digdag.env.export ,
digdag.env.add_subtask may be one way.
```
def set_export_and_run_child():
    digdag.env.export({"table": "carried information"})
    digdag.env.add_subtask({
        '_type': 'call',
        '_command': 'child1.dig'
        })
```

**Comment by muga** [comment]
@sonots It depends on what you want to do with export variables but, if you want to pass variables to following tasks, you'd better to use store parameters as mentioned by @yoyama. But store parameters will be stored and updated on Digdag database. Moreover UI shows the values as you mentioned above.

If you want to pass credentials to the following tasks, what do you think that you put them in secret store via REST API directly? (Or as possible improvement in Digdag, we could introduce REST API for param_set/get operators. In the current implementation, param_set/get operators directly store params to data store directly. Your ruby/python program could call the API endpoints instead of the operators to store values and then, the following tasks could fetch them from data store. In the current implementation, param_set/get operators directly store params to data store directly though.)

**Comment by sonots** [comment]
My final purpose was to use secrets in embulk liquid files and in docker containers.

To do it, I needed to map all secrets to environment variables, and I tried to use digdag.env.store and digdag.env.export. This is the background of this story.

I wrote details at https://qiita.com/sonots/items/cb71834857235f965225 (Japanese)

For this purpose, I feel good if following is supported.

1. Add a python API to get secrets (so that I do not need to write _env)
2. Add an option to digdag.env.store to hide from web ui (and somewhere else it would be seen)

But, anyway, I found that digdag.env.export is not working as we expected. I reported about it here. I think that the example and doc must be fixed to close this issue.
