### ISSUE TITLE
[feature request] Get current system config parameter.

### ISSUE THREAD

**Issue by hiroyuki-sato** [treasure-data/digdag#999]
As discussed https://github.com/treasure-data/digdag/pull/994#discussion_r258405429,
users want to know the current system config parameter. 
For example: `api.max_attempts_page_size`

There are two ideas.

* Output current parameters into a log at server launch time.
* Introduce new API `/api/admin/system/configs` and client command like `digdag server_config`.

Any idea?

**Comment by muga** [comment]
@hiroyuki-sato thank you for heading up it from #994.

It seems that the original requirement is to provide how to check if system config parameters declared by users are effectively applied or not. To know that they are applied or not, logging is good. But they can not be shown at bootstrap because we don't know when some of them will be applied or not. 

@yoyama @sonots Do you have any thoughts? any idea?

**Comment by sonots** [comment]
Even if the parameter is not truly applied yet, showing values of configuration on booting time helps users to check his typo and whether his version of digdag supports its config parameter.

I feel it is fine enough.

**Comment by muga** [comment]
@sonots Thanks, that's not complicated.

Digdag reads system config params from files at bootstrap time, and then it can show the params on the log file. My current concern is that Digdag doesn't know a config param looks like credentials or not at the bootstrap time. I don't want Digdag to write the database password in the log file. hm.

**Comment by muga** [comment]
digdag-server bootstrap time is different from time when a constructor is called on each resource endpoints. Those instantiation is controlled by guice if my understanding is correct. @yoyama What do you think that we'd better to inject those resource in server module as eager mode?
